// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hbdfcmyfbsfkgrgnqhfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiZGZjbXlmYnNma2dyZ25xaGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjU3ODYsImV4cCI6MjA2MTIwMTc4Nn0.6w-BMxTQfrBriYzNiSw19SpwrtitHJCnHVHbF2dWxDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);